name: fail
on:
  pull_request:
    branches: [main]  

    
jobs:
  dummy_test:
    runs-on: ubuntu-latest
    steps:
        # Check if a file under major/ or with the .txt extension has changed (added, modified, deleted)
         $SourceDiff = $diff | Where-Object { $_ -match '^major/' -or $_ -match '.txt$' }
         $HasDiff = $SourceDiff.Length -gt 0
  if: steps.check_file_changed.outputs.docs_changed == 'True'
      - run:echo 'Make renovate automerge excuted'
      -  run:exit 1
      - name:Print message if we don't fail
        run:echo Should not get here
